### ISSUE TITLE
NTSC framerate correction changing 30000/1001 to 30001/1001...

### ISSUE THREAD

**Issue by quarkboy** [FFMS/ffms2#168]
When loading files encoded at 30000/1001 fps (29.97), the function CorrectNTSCRationalFramerate in videoutils "corrects" it to 30001/1001 (29.971)

This is especially annoying in aegisub for subtitle timing purposes as it makes timings go off by 2 frames every 30 minutes or so.

The bug is in line 97 of videoutils.cpp:

*Num = int((1001.0 / FTimebase) + 0.5);
should be
*Num = floor((1001.0 / FTimebase) + 0.5);

**Comment by ValdikSS** [comment]
25 fps video is detected as 25060/1001 fps (25.03)

**Comment by myrsloik** [comment]
int(positive float) and floor(positive float) are the same operation so that's not the real issue.

I think that code never worked properly. I think it'd be better to replace it with a list of common framerates and compare to see if the current one is close to one. The current code (if I'm not mistaken) simply seems to have a bias for make framerates x/1001. Which gives fun results like 30001/1001.

I think the best solution would be to replace it with a list of common framerates and see if any of them are close. My suggested list for the first attempt: (24000, 30000, 60000, 120000)/1001 and 24, 25, 30, 60, 120 fps.

Have a look at the current code here if you want to ponder it yourselves:
https://github.com/FFMS/ffms2/blob/master/src/core/videoutils.cpp#L80

**Comment by myrsloik** [comment]
I've replaced the code completely now. Compile and try it yourself or tell me if you need a compile to see if my new idea is better.
