### ISSUE TITLE
interoperability with avxsynth broken

### ISSUE THREAD

**Issue by kaefert** [FFMS/ffms2#184]
The commit 7847d0de1b7706e24e82bdaedf1b6fe09334294d in this repository causes this issue with avxsynth for me:
With the latest version from repository any call to ffms2 like FFVideoSource() makes avxsynth hang indefinitely

For a more detailed explanation see:
https://github.com/avxsynth/avxsynth/issues/110

The last commit that works for me is this one 08f94eea89fa3de4f68184f8c7eebe32a21130a8
`git checkout 08f94eea89fa3de4f68184f8c7eebe32a21130a8`

**Comment by avxsynth-testing** [comment]
I'm pretty sure compatibility with FFmpeg avisynth.c demuxer is broken, not specifically for AvxSynth. Any case where mpv and ffms2 share a ffmpeg library will be broken because mpv is registering an avformat mutex which is recursively acquired first by avisynth.c and then by ffms2. The correct solution is to coordinate initialization of ffmpeg (avformat_network_init) between the libraries or to not register avformat mutexes to begin with.
