### ISSUE TITLE
Frames that could (should?) be skipped because of metadata, aren't

### ISSUE THREAD

**Issue by nixxquality** [FFMS/ffms2#192]
If I understand what's causing this issue, it's when the video framerate doesn't match up with the amount of frames in the video stream, and when FFMS2 should be skipping frames, it doesn't.

God knows why this metadata exists in the first place. In MPC it's listed like this:
```
Frame rate          : 23.810 fps
Original frame rate : 23.976 fps
```

Here is [a test file](https://mega.co.nz/#!f4gnHK6b!-aE4VOGeE4XHVP6MaUen1mhb8mSkvHx0FpHrIFmaUi8) that shows this issue.
According to MPC, this file has 383 frames; according to FFMS2 (and ffmpeg) it has 387.

I'm not sure what the exact cause for this is, and I'm not sure what the "proper way" to handle this is.

**Comment by qyot27** [comment]
There is a long-standing known issue with MediaInfo's Matroska parsing algorithms (it even came up again recently in the mkvtoolnix thread on Doom9).  I wouldn't be surprised if this issue has that as a complicating factor.

I'm not seeing that big of a difference in result from here, though:
```
>mediainfo -f "original framerate test file.mkv" | grep -i "frame"
Complete name                            : original framerate test file.mkv
File name                                : original framerate test file
Frame rate                               : 23.976
Frame rate                               : 23.976 fps
Frame count                              : 388
Format settings                          : CABAC / 6 Ref Frames
Format settings, ReFrames                : 6
Format settings, ReFrames                : 6 frames
Codec settings                           : CABAC / 6 Ref Frames
Codec_Settings_RefFrames                 : 6
Frame rate mode                          : CFR
Frame rate mode                          : Constant
Frame rate                               : 23.976
Frame rate                               : 23.976 fps
Frame count                              : 388
Bits/(Pixel*Frame)                       : 0.080
```

That's with an SVN build of MediaInfo from yesterday afternoon/evening.

MPC-HC's internal MediaInfo dialog in Properties shows just Frame rate: 23.976, no Original Frame Rate field at all.  It's a slightly older version: 0.7.71 rather than the SVN/0.7.72 I was using, but they seem to agree.

**Comment by nixxquality** [comment]
So, would you say the fault is on MPC for displaying the wrong frames?

**Comment by qyot27** [comment]
I don't know.  I know nothing about MPC's internals to say where the discrepancy actually appears.

**Comment by dwbuiten** [comment]
This is not metadata.

Four of the video frames in this file have duplicate timestamps:
```
[null @ 0x2d3f4a0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 1 >= 1
[null @ 0x2d3f4a0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 73 >= 73
[null @ 0x2d3f4a0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 216 >= 216
[null @ 0x2d3f4a0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 359 >= 359
```

So MPC drops them, since the display time is technically impossible, and FFMS2 keeps them around.

There is no "correct" way to handle them, and this bug should be marked as closed. The file is broken, not the software.

**Comment by tgoyne** [comment]
I'd actually say that both ffms2 and mpc are handling them in the correct ways for their respective roles.
