### ISSUE TITLE
Cannot open Apple Prores MOV

### ISSUE THREAD

**Issue by belonesox** [FFMS/ffms2#336]
Have videos like that:

```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '2018-10-13-13-17-32-NINJA2_S001_S001_T011.MOV':
  Metadata:
    major_brand     : qt
    minor_version   : 537199360
    compatible_brands: qt
    creation_time   : 2018-10-13 13:17:33
    make            : ?
    encoder         : ?
    timecode        : 00:00:00:00
  Duration: 00:00:04.68, start: 0.000000, bitrate: 77328 kb/s
    Stream #0:0(eng): Audio: pcm_s16le (sowt / 0x74776F73), 48000 Hz, 2 channels, s16, 1536 kb/s (default)
    Metadata:
      creation_time   : 2018-10-13 13:17:33
    Stream #0:1(eng): Video: prores (apcs / 0x73637061), yuv422p10le(bt709), 1920x1080, 72089 kb/s, SAR 1:1 DAR 16:9, 25 fps, 25 tbr, 2500 tbn (default)
    Metadata:
      creation_time   : 2018-10-13 13:17:33
      encoder         : Apple ProRes 422 (LT)
    Stream #0:2(eng): Data: none (tmcd / 0x64636D74), 0 kb/s (default)
    Metadata:
      creation_time   : 2018-10-13 13:17:33
      timecode        : 00:00:00:00
```
https://drive.google.com/open?id=13rtdpOeBZjkmS3IQFH8LNxJi4D-xWV6f
43Mb

ffmpeg/ffplay works OK.

I tried FFMS from "ffms2_r1327+119-avs+vsp.7z" 
got:
``
[avisynth @ 05807b60] FFVideoSource: No suitable output format found
(FFMS2.avsi, line 36)
``

?

**Comment by qyot27** [comment]
It's the C plugin.  The revision number gives it away (both that it has one and how the number is calculated/formatted).

A) https://github.com/qyot27/ffms2_cplugin/issues is where issues with the C plugin should go now.  I hadn't bothered enabling it until now because usually issues are just posted to the Doom9 thread.

B) That's expected behavior when trying to open high bit depth content with the C plugin in AviSynth 2.6 - the C plugin will not do automatic downsampling to 8-bit.  Use the *colorspace=* parameter to force convert it at load, or use AviSynth+ to preserve the high bit depth and/or dither it down with ConvertBits() or avsresize() or whatever.
