### ISSUE TITLE
ffms2 2.40 osx build issue

### ISSUE THREAD

**Issue by chenrui333** [FFMS/ffms2#371]
👋 trying to bump homebrew formula version to the latest, but run into some issue.

Full build log, https://github.com/Homebrew/homebrew-core/runs/1029378871
relates to https://github.com/Homebrew/homebrew-core/pull/60178

**Comment by dwbuiten** [comment]
The GitHub-generated tarball no longer contains `configure` since we stopped checking it into the git repo.

"Solutions" are:

- Update the brew recipe to always use autogen and install automake/autoconf (it already does this for git HEAD).
- or: Upload a manually created tarball (`make dist-xz` or whatever) that includes configure to the release page to be more in-line with what users would expect from a tarball.

@myrsloik Any opinion? I have no strong feeling towards either.

**Comment by myrsloik** [comment]
I feel nothing

**Comment by chenrui333** [comment]
Thanks for the direction, I will give autogen a shot tonight.

**Comment by chenrui333** [comment]
yeah, I think it works out for me. I will close the issue once we merged the PR.
