### ISSUE TITLE
vcpkg support

### ISSUE THREAD

**Issue by SamuelMarks** [FFMS/ffms2#383]
`zlib` and `ffmpeg` are both included in vcpkg. Just tried on macOS and found FFMPEG built with:
> --enable-pic --disable-doc --enable-debug --enable-runtime-cpudetect --enable-asm --enable-x86asm --enable-gpl --disable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --enable-postproc --enable-swresample --enable-swscale --enable-avresample --disable-libass --disable-avisynth --disable-bzlib --disable-libdav1d --disable-iconv --disable-libilbc --disable-libfdk-aac --disable-libfontconfig --disable-libfreetype --disable-libfribidi --disable-lzma --disable-libmp3lame --disable-libmodplug --disable-cuda --disable-nvenc --disable-nvdec  --disable-cuvid --disable-ffnvcodec --disable-opencl --disable-opengl --disable-libopenjpeg --disable-openssl --disable-libopus --disable-sdl2 --disable-libsnappy --disable-libsoxr --disable-libspeex --disable-libssh --disable-libtensorflow --disable-libtesseract --disable-libtheora --disable-libvorbis --disable-libvpx --disable-libwavpack --disable-libwebp --disable-libx264 --disable-libx265 --disable-libxml2 --disable-zlib --disable-vdpau  --pkg-config-flags=--static

What do you think about vcpkg?

I can give a shot at implementing a package for it, but it tends to be easier with CMake or Meson (CMake is especially easier). Although Makefiles are now supported as of a few weeks ago, so can probably make it work without too many changes…

**Comment by wrosecrans** [comment]
Has any thought be given to switching (back) to CMake?  It would simplify using FFMS2 with vcpkg.  I've been using vcpkg to build ffmpeg (and the pile of dependencies for it), and I've got a fork of ffms2 with a CMake build system that finds my FFMPEG build without any issues: https://github.com/wrosecrans/ffms2/blob/master/CMakeLists.txt

Basically, vcpkg just sets up the search directory variables so that vanilla CMake knows where to look for library dependencies.  Then in the FFMS2 build, I only need a `find_package(FFmpeg REQUIRED)` -- nothing vcpkg specific.

Looking through the FFMS2 history, it looks like there used to be a CMake build system, but it got abandoned.  In the mean time, CMake has gotten a lot more mature, and common enough to practically be the de facto build system for C++, so it may be the path of least resistance going forward.  (And I say that as someone who doesn't particularly _like_ CMake as a language.)

**Comment by myrsloik** [comment]
We provide compiled binaries and matching .lib files for download. This is compatible with all build systems.
