### ISSUE TITLE
video is unseekable

### ISSUE THREAD

**Issue by BobDLA** [FFMS/ffms2#407]
Hi,
   Thanks for your great work. 
   I have some videos that could play and seekable by vlc(one demo as the attachment), but got "**Video track is unseekable**" when FFMS_CreateVideoSource. 
   Could you help to check what cause the error and how to workaround?
   System info :
    Ubuntu 20.04 , ffmpeg version 4.2.7, ffms with commit ff61bca13e2c5fb99c0450620c9244f415ec29c4
   (other system should have the save issue also)

Thanks

https://user-images.githubusercontent.com/3804610/186893184-8e549fd8-56b1-4607-b1b8-e43c304fb540.mp4

**Comment by myrsloik** [comment]
A bit late to reply but this happens when FFmpeg can't seek to the first frame in a file successfully meaning that it can never rewind all the way. Sometimes FFmpeg is this way. Exactly why it fails here I have no idea, mp4 usually works flawlessly. Open with Seekmode=-1 or 0 I guess. Or use BestSource that's a bit more reliable for small clips.
